//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucene.Net.CodeAnalysis.Dev {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lucene.Net.CodeAnalysis.Dev.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating point types should not be compared for exact equality..
        /// </summary>
        internal static string LuceneDev1000_AnalyzerDescription {
            get {
                return ResourceManager.GetString("LuceneDev1000_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; may fail due to JIT optimizations. Floating point types should not be compared for exact equality..
        /// </summary>
        internal static string LuceneDev1000_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("LuceneDev1000_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating point types should not be compared for exact equality..
        /// </summary>
        internal static string LuceneDev1000_AnalyzerTitle {
            get {
                return ResourceManager.GetString("LuceneDev1000_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating point types should be formatted with J2N.Numerics.Single.ToString() or J2N.Numerics.Double.ToString()..
        /// </summary>
        internal static string LuceneDev1001_AnalyzerDescription {
            get {
                return ResourceManager.GetString("LuceneDev1001_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; may fail due to floating point precision issues on .NET Framework and .NET Core prior to version 3.0. Floating point types should be formatted with J2N.Numerics.Single.ToString() or J2N.Numerics.Double.ToString()..
        /// </summary>
        internal static string LuceneDev1001_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("LuceneDev1001_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating point types should be formatted with J2N.Numerics.Single.ToString() or J2N.Numerics.Double.ToString()..
        /// </summary>
        internal static string LuceneDev1001_AnalyzerTitle {
            get {
                return ResourceManager.GetString("LuceneDev1001_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating point type arithmetic needs to be checked on x86 in .NET Framework..
        /// </summary>
        internal static string LuceneDev1002_AnalyzerDescription {
            get {
                return ResourceManager.GetString("LuceneDev1002_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; may fail due to floating point precision issues on .NET Framework and .NET Core prior to version 3.0. Floating point type arithmetic needs to be checked on x86 in .NET Framework and may require extra casting..
        /// </summary>
        internal static string LuceneDev1002_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("LuceneDev1002_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating point type arithmetic needs to be checked on x86 in .NET Framework..
        /// </summary>
        internal static string LuceneDev1002_AnalyzerTitle {
            get {
                return ResourceManager.GetString("LuceneDev1002_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method parameters that accept array types should be analyzed to determine whether they are better suited to be ref or out parameters..
        /// </summary>
        internal static string LuceneDev1003_AnalyzerDescription {
            get {
                return ResourceManager.GetString("LuceneDev1003_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; needs to be analyzed to determine whether the array can be replaced with a ref or out parameter..
        /// </summary>
        internal static string LuceneDev1003_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("LuceneDev1003_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method parameters that accept array types should be analyzed to determine whether they are better suited to be ref or out parameters..
        /// </summary>
        internal static string LuceneDev1003_AnalyzerTitle {
            get {
                return ResourceManager.GetString("LuceneDev1003_AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods that return array types should be analyzed to determine whether they are better suited to be one or more out parameters or to return a ValueTuple..
        /// </summary>
        internal static string LuceneDev1004_AnalyzerDescription {
            get {
                return ResourceManager.GetString("LuceneDev1004_AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; return type needs to be analyzed to determine whether the array return value can be replaced with one or more out parameters or a return ValueTuple instead of an array to avoid the heap allocation..
        /// </summary>
        internal static string LuceneDev1004_AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("LuceneDev1004_AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods that return array types should be analyzed to determine whether they are better suited to be one or more out parameters or to return a ValueTuple..
        /// </summary>
        internal static string LuceneDev1004_AnalyzerTitle {
            get {
                return ResourceManager.GetString("LuceneDev1004_AnalyzerTitle", resourceCulture);
            }
        }
    }
}
